using Microsoft.EntityFrameworkCore;
using PRN232.LMS.Repositories.Entities;
using PRN232.LMS.Repositories.Repositories;
using PRN232.LMS.Services.Models;

namespace PRN232.LMS.Services.Services;

public interface ILmsService
{
    Task<PagedResult> GetSemestersAsync(ListQuery q); Task<SemesterResponse?> GetSemesterAsync(int id); Task<(SemesterResponse? Data, string? Error)> CreateSemesterAsync(SemesterRequest r); Task<(bool Found, string? Error)> UpdateSemesterAsync(int id, SemesterRequest r); Task<bool> DeleteSemesterAsync(int id);
    Task<PagedResult> GetSubjectsAsync(ListQuery q); Task<SubjectResponse?> GetSubjectAsync(int id); Task<(SubjectResponse? Data, string? Error)> CreateSubjectAsync(SubjectRequest r); Task<(bool Found, string? Error)> UpdateSubjectAsync(int id, SubjectRequest r); Task<bool> DeleteSubjectAsync(int id);
    Task<PagedResult> GetCoursesAsync(ListQuery q); Task<CourseResponse?> GetCourseAsync(int id); Task<(CourseResponse? Data, string? Error)> CreateCourseAsync(CourseRequest r); Task<(bool Found, string? Error)> UpdateCourseAsync(int id, CourseRequest r); Task<bool> DeleteCourseAsync(int id);
    Task<PagedResult> GetStudentsAsync(ListQuery q); Task<StudentResponse?> GetStudentAsync(int id); Task<(StudentResponse? Data, string? Error)> CreateStudentAsync(StudentRequest r); Task<(bool Found, string? Error)> UpdateStudentAsync(int id, StudentRequest r); Task<bool> DeleteStudentAsync(int id);
    Task<PagedResult> GetEnrollmentsAsync(ListQuery q); Task<EnrollmentResponse?> GetEnrollmentAsync(int id); Task<(EnrollmentResponse? Data, string? Error)> CreateEnrollmentAsync(EnrollmentRequest r); Task<(bool Found, string? Error)> UpdateEnrollmentAsync(int id, EnrollmentRequest r); Task<bool> DeleteEnrollmentAsync(int id);
}

public class LmsService(ILmsRepository repo) : ILmsService
{
    static HashSet<string> Parts(string? value) => (value ?? "").Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).ToHashSet(StringComparer.OrdinalIgnoreCase);
    static void Validate(ListQuery q, IEnumerable<string> sortable, IEnumerable<string> selectable, IEnumerable<string>? expandable = null)
    {
        static IEnumerable<string> SortParts(string? value) => (value ?? "").Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).Select(x => x.TrimStart('-'));
        var sortSet = sortable.ToHashSet(StringComparer.OrdinalIgnoreCase);
        var fieldSet = selectable.ToHashSet(StringComparer.OrdinalIgnoreCase);
        var expandSet = (expandable ?? []).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var badSort = SortParts(q.Sort).FirstOrDefault(x => !sortSet.Contains(x));
        var badField = Parts(q.Fields).FirstOrDefault(x => !fieldSet.Contains(x));
        var badExpand = Parts(q.Expand).FirstOrDefault(x => !expandSet.Contains(x));
        if (badSort is not null) throw new ArgumentException($"Unknown sort field '{badSort}'.");
        if (badField is not null) throw new ArgumentException($"Unknown fields value '{badField}'.");
        if (badExpand is not null) throw new ArgumentException($"Unknown expand value '{badExpand}'.");
    }
    static object Select(object item, string? fields)
    {
        var wanted = Parts(fields); if (wanted.Count == 0) return item;
        return item.GetType().GetProperties().Where(p => wanted.Contains(p.Name)).ToDictionary(p => char.ToLowerInvariant(p.Name[0]) + p.Name[1..], p => p.GetValue(item));
    }
    static async Task<PagedResult> PageAsync<T>(IQueryable<T> query, ListQuery q, Func<T, object> map)
    {
        var count = await query.CountAsync();
        var rows = await query.Skip((q.Page - 1) * q.Size).Take(q.Size).ToListAsync();
        return new(rows.Select(x => Select(map(x), q.Fields)).ToList(), new(q.Page, q.Size, count, (int)Math.Ceiling(count / (double)q.Size)));
    }
    static IOrderedQueryable<T> Order<T>(IQueryable<T> query, string? sort, IReadOnlyDictionary<string, System.Linq.Expressions.Expression<Func<T, object>>> map, System.Linq.Expressions.Expression<Func<T, object>> fallback)
    {
        IOrderedQueryable<T>? ordered = null;
        foreach (var token in (sort ?? "").Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var desc = token.StartsWith('-'); var key = desc ? token[1..] : token;
            if (!map.TryGetValue(key, out var exp)) continue;
            ordered = ordered is null ? (desc ? query.OrderByDescending(exp) : query.OrderBy(exp)) : (desc ? ordered.ThenByDescending(exp) : ordered.ThenBy(exp));
        }
        return ordered ?? query.OrderBy(fallback);
    }

    public Task<PagedResult> GetSemestersAsync(ListQuery q)
    {
        Validate(q, ["semesterId", "semesterName", "startDate", "endDate"], ["semesterId", "semesterName", "startDate", "endDate", "courses"], ["courses"]);
        var ex = Parts(q.Expand); var query = repo.Semesters.Where(x => q.Search == null || x.SemesterName.Contains(q.Search));
        query = Order(query, q.Sort, new Dictionary<string, System.Linq.Expressions.Expression<Func<Semester, object>>>(StringComparer.OrdinalIgnoreCase) { ["semesterId"] = x => x.SemesterId, ["semesterName"] = x => x.SemesterName, ["startDate"] = x => x.StartDate, ["endDate"] = x => x.EndDate }, x => x.SemesterId);
        if (ex.Contains("courses")) query = query.Include(x => x.Courses);
        return PageAsync(query, q, x => new SemesterResponse(x.SemesterId, x.SemesterName, x.StartDate, x.EndDate, ex.Contains("courses") ? x.Courses.Select(c => new { c.CourseId, c.CourseName, c.SubjectId }) : null));
    }
    public async Task<SemesterResponse?> GetSemesterAsync(int id) { var x = await repo.Semesters.Include(x => x.Courses).SingleOrDefaultAsync(x => x.SemesterId == id); return x is null ? null : new(x.SemesterId, x.SemesterName, x.StartDate, x.EndDate, x.Courses.Select(c => new { c.CourseId, c.CourseName, c.SubjectId })); }
    public async Task<(SemesterResponse?, string?)> CreateSemesterAsync(SemesterRequest r) { if (r.EndDate <= r.StartDate) return (null, "EndDate must be after StartDate."); var x = new Semester { SemesterName = r.SemesterName.Trim(), StartDate = r.StartDate, EndDate = r.EndDate }; await repo.AddAsync(x); await repo.SaveChangesAsync(); return (new(x.SemesterId, x.SemesterName, x.StartDate, x.EndDate), null); }
    public async Task<(bool, string?)> UpdateSemesterAsync(int id, SemesterRequest r) { var x = await repo.FindAsync<Semester>(id); if (x is null) return (false, null); if (r.EndDate <= r.StartDate) return (true, "EndDate must be after StartDate."); x.SemesterName = r.SemesterName.Trim(); x.StartDate = r.StartDate; x.EndDate = r.EndDate; await repo.SaveChangesAsync(); return (true, null); }
    public async Task<bool> DeleteSemesterAsync(int id) { var x = await repo.FindAsync<Semester>(id); if (x is null) return false; repo.Remove(x); await repo.SaveChangesAsync(); return true; }

    public Task<PagedResult> GetSubjectsAsync(ListQuery q) { Validate(q, ["subjectId", "subjectCode", "subjectName", "credit"], ["subjectId", "subjectCode", "subjectName", "credit"]); var query = repo.Subjects.Where(x => q.Search == null || x.SubjectName.Contains(q.Search) || x.SubjectCode.Contains(q.Search)); query = Order(query, q.Sort, new Dictionary<string, System.Linq.Expressions.Expression<Func<Subject, object>>>(StringComparer.OrdinalIgnoreCase) { ["subjectId"] = x => x.SubjectId, ["subjectCode"] = x => x.SubjectCode, ["subjectName"] = x => x.SubjectName, ["credit"] = x => x.Credit }, x => x.SubjectId); return PageAsync(query, q, x => new SubjectResponse(x.SubjectId, x.SubjectCode, x.SubjectName, x.Credit)); }
    public async Task<SubjectResponse?> GetSubjectAsync(int id) { var x = await repo.Subjects.Include(x => x.Courses).SingleOrDefaultAsync(x => x.SubjectId == id); return x is null ? null : new(x.SubjectId, x.SubjectCode, x.SubjectName, x.Credit, x.Courses.Select(c => new { c.CourseId, c.CourseName, c.SemesterId })); }
    public async Task<(SubjectResponse?, string?)> CreateSubjectAsync(SubjectRequest r) { if (await repo.Subjects.AnyAsync(x => x.SubjectCode == r.SubjectCode)) return (null, "SubjectCode already exists."); var x = new Subject { SubjectCode = r.SubjectCode.Trim().ToUpperInvariant(), SubjectName = r.SubjectName.Trim(), Credit = r.Credit }; await repo.AddAsync(x); await repo.SaveChangesAsync(); return (new(x.SubjectId, x.SubjectCode, x.SubjectName, x.Credit), null); }
    public async Task<(bool, string?)> UpdateSubjectAsync(int id, SubjectRequest r) { var x = await repo.FindAsync<Subject>(id); if (x is null) return (false, null); if (await repo.Subjects.AnyAsync(s => s.SubjectCode == r.SubjectCode && s.SubjectId != id)) return (true, "SubjectCode already exists."); x.SubjectCode = r.SubjectCode.Trim().ToUpperInvariant(); x.SubjectName = r.SubjectName.Trim(); x.Credit = r.Credit; await repo.SaveChangesAsync(); return (true, null); }
    public async Task<bool> DeleteSubjectAsync(int id) { var x = await repo.FindAsync<Subject>(id); if (x is null) return false; repo.Remove(x); await repo.SaveChangesAsync(); return true; }

    public Task<PagedResult> GetCoursesAsync(ListQuery q) { Validate(q, ["courseId", "courseName", "semesterId", "subjectId"], ["courseId", "courseName", "semesterId", "subjectId", "semester", "subject", "enrollments"], ["semester", "subject", "enrollments"]); var ex = Parts(q.Expand); var query = repo.Courses.Where(x => (q.Search == null || x.CourseName.Contains(q.Search)) && (q.SemesterId == null || x.SemesterId == q.SemesterId) && (q.SubjectId == null || x.SubjectId == q.SubjectId)); query = Order(query, q.Sort, new Dictionary<string, System.Linq.Expressions.Expression<Func<Course, object>>>(StringComparer.OrdinalIgnoreCase) { ["courseId"] = x => x.CourseId, ["courseName"] = x => x.CourseName, ["semesterId"] = x => x.SemesterId, ["subjectId"] = x => x.SubjectId }, x => x.CourseId); if (ex.Contains("semester")) query = query.Include(x => x.Semester); if (ex.Contains("subject")) query = query.Include(x => x.Subject); if (ex.Contains("enrollments")) query = query.Include(x => x.Enrollments); return PageAsync(query, q, x => new CourseResponse(x.CourseId, x.CourseName, x.SemesterId, x.SubjectId, ex.Contains("semester") ? new { x.Semester.SemesterId, x.Semester.SemesterName } : null, ex.Contains("subject") ? new { x.Subject.SubjectId, x.Subject.SubjectCode, x.Subject.SubjectName, x.Subject.Credit } : null, ex.Contains("enrollments") ? x.Enrollments.Select(e => new { e.EnrollmentId, e.StudentId, e.EnrollDate, e.Status }) : null)); }
    public async Task<CourseResponse?> GetCourseAsync(int id) { var x = await repo.Courses.Include(x => x.Semester).Include(x => x.Subject).Include(x => x.Enrollments).SingleOrDefaultAsync(x => x.CourseId == id); return x is null ? null : new(x.CourseId, x.CourseName, x.SemesterId, x.SubjectId, new { x.Semester.SemesterId, x.Semester.SemesterName, x.Semester.StartDate, x.Semester.EndDate }, new { x.Subject.SubjectId, x.Subject.SubjectCode, x.Subject.SubjectName, x.Subject.Credit }, x.Enrollments.Select(e => new { e.EnrollmentId, e.StudentId, e.EnrollDate, e.Status })); }
    public async Task<(CourseResponse?, string?)> CreateCourseAsync(CourseRequest r) { if (await repo.Semesters.SingleOrDefaultAsync(x => x.SemesterId == r.SemesterId) is null || await repo.Subjects.SingleOrDefaultAsync(x => x.SubjectId == r.SubjectId) is null) return (null, "SemesterId or SubjectId does not exist."); var x = new Course { CourseName = r.CourseName.Trim(), SemesterId = r.SemesterId, SubjectId = r.SubjectId }; await repo.AddAsync(x); await repo.SaveChangesAsync(); return (new(x.CourseId, x.CourseName, x.SemesterId, x.SubjectId), null); }
    public async Task<(bool, string?)> UpdateCourseAsync(int id, CourseRequest r) { var x = await repo.FindAsync<Course>(id); if (x is null) return (false, null); if (await repo.Semesters.SingleOrDefaultAsync(s => s.SemesterId == r.SemesterId) is null || await repo.Subjects.SingleOrDefaultAsync(s => s.SubjectId == r.SubjectId) is null) return (true, "SemesterId or SubjectId does not exist."); x.CourseName = r.CourseName.Trim(); x.SemesterId = r.SemesterId; x.SubjectId = r.SubjectId; await repo.SaveChangesAsync(); return (true, null); }
    public async Task<bool> DeleteCourseAsync(int id) { var x = await repo.FindAsync<Course>(id); if (x is null) return false; repo.Remove(x); await repo.SaveChangesAsync(); return true; }

    public Task<PagedResult> GetStudentsAsync(ListQuery q) { Validate(q, ["studentId", "fullName", "email", "dateOfBirth"], ["studentId", "fullName", "email", "dateOfBirth", "enrollments"], ["enrollments"]); var ex = Parts(q.Expand); var query = repo.Students.Where(x => q.Search == null || x.FullName.Contains(q.Search) || x.Email.Contains(q.Search)); query = Order(query, q.Sort, new Dictionary<string, System.Linq.Expressions.Expression<Func<Student, object>>>(StringComparer.OrdinalIgnoreCase) { ["studentId"] = x => x.StudentId, ["fullName"] = x => x.FullName, ["email"] = x => x.Email, ["dateOfBirth"] = x => x.DateOfBirth }, x => x.StudentId); if (ex.Contains("enrollments")) query = query.Include(x => x.Enrollments); return PageAsync(query, q, x => new StudentResponse(x.StudentId, x.FullName, x.Email, x.DateOfBirth, ex.Contains("enrollments") ? x.Enrollments.Select(e => new { e.EnrollmentId, e.CourseId, e.EnrollDate, e.Status }) : null)); }
    public async Task<StudentResponse?> GetStudentAsync(int id) { var x = await repo.Students.Include(x => x.Enrollments).ThenInclude(e => e.Course).SingleOrDefaultAsync(x => x.StudentId == id); return x is null ? null : new(x.StudentId, x.FullName, x.Email, x.DateOfBirth, x.Enrollments.Select(e => new { e.EnrollmentId, e.EnrollDate, e.Status, course = new { e.Course.CourseId, e.Course.CourseName } })); }
    public async Task<(StudentResponse?, string?)> CreateStudentAsync(StudentRequest r) { if (r.DateOfBirth >= DateTime.Today) return (null, "DateOfBirth must be in the past."); if (await repo.Students.AnyAsync(x => x.Email == r.Email)) return (null, "Email already exists."); var x = new Student { FullName = r.FullName.Trim(), Email = r.Email.Trim().ToLowerInvariant(), DateOfBirth = r.DateOfBirth }; await repo.AddAsync(x); await repo.SaveChangesAsync(); return (new(x.StudentId, x.FullName, x.Email, x.DateOfBirth), null); }
    public async Task<(bool, string?)> UpdateStudentAsync(int id, StudentRequest r) { var x = await repo.FindAsync<Student>(id); if (x is null) return (false, null); if (r.DateOfBirth >= DateTime.Today) return (true, "DateOfBirth must be in the past."); if (await repo.Students.AnyAsync(s => s.Email == r.Email && s.StudentId != id)) return (true, "Email already exists."); x.FullName = r.FullName.Trim(); x.Email = r.Email.Trim().ToLowerInvariant(); x.DateOfBirth = r.DateOfBirth; await repo.SaveChangesAsync(); return (true, null); }
    public async Task<bool> DeleteStudentAsync(int id) { var x = await repo.FindAsync<Student>(id); if (x is null) return false; repo.Remove(x); await repo.SaveChangesAsync(); return true; }

    public Task<PagedResult> GetEnrollmentsAsync(ListQuery q) { Validate(q, ["enrollmentId", "studentId", "courseId", "enrollDate", "status"], ["enrollmentId", "studentId", "courseId", "enrollDate", "status", "student", "course"], ["student", "course"]); var ex = Parts(q.Expand); var query = repo.Enrollments.Where(x => (q.Search == null || x.Status.Contains(q.Search)) && (q.Status == null || x.Status == q.Status) && (q.StudentId == null || x.StudentId == q.StudentId) && (q.CourseId == null || x.CourseId == q.CourseId)); query = Order(query, q.Sort, new Dictionary<string, System.Linq.Expressions.Expression<Func<Enrollment, object>>>(StringComparer.OrdinalIgnoreCase) { ["enrollmentId"] = x => x.EnrollmentId, ["studentId"] = x => x.StudentId, ["courseId"] = x => x.CourseId, ["enrollDate"] = x => x.EnrollDate, ["status"] = x => x.Status }, x => x.EnrollmentId); if (ex.Contains("student")) query = query.Include(x => x.Student); if (ex.Contains("course")) query = query.Include(x => x.Course); return PageAsync(query, q, x => new EnrollmentResponse(x.EnrollmentId, x.StudentId, x.CourseId, x.EnrollDate, x.Status, ex.Contains("student") ? new { x.Student.StudentId, x.Student.FullName, x.Student.Email } : null, ex.Contains("course") ? new { x.Course.CourseId, x.Course.CourseName, x.Course.SemesterId, x.Course.SubjectId } : null)); }
    public async Task<EnrollmentResponse?> GetEnrollmentAsync(int id) { var x = await repo.Enrollments.Include(x => x.Student).Include(x => x.Course).ThenInclude(c => c.Semester).Include(x => x.Course).ThenInclude(c => c.Subject).SingleOrDefaultAsync(x => x.EnrollmentId == id); return x is null ? null : new(x.EnrollmentId, x.StudentId, x.CourseId, x.EnrollDate, x.Status, new { x.Student.StudentId, x.Student.FullName, x.Student.Email, x.Student.DateOfBirth }, new { x.Course.CourseId, x.Course.CourseName, semester = new { x.Course.Semester.SemesterId, x.Course.Semester.SemesterName }, subject = new { x.Course.Subject.SubjectId, x.Course.Subject.SubjectCode, x.Course.Subject.SubjectName } }); }
    public async Task<(EnrollmentResponse?, string?)> CreateEnrollmentAsync(EnrollmentRequest r) { if (await repo.Students.SingleOrDefaultAsync(x => x.StudentId == r.StudentId) is null || await repo.Courses.SingleOrDefaultAsync(x => x.CourseId == r.CourseId) is null) return (null, "StudentId or CourseId does not exist."); if (await repo.Enrollments.AnyAsync(x => x.StudentId == r.StudentId && x.CourseId == r.CourseId)) return (null, "Student is already enrolled in this course."); var x = new Enrollment { StudentId = r.StudentId, CourseId = r.CourseId, EnrollDate = r.EnrollDate, Status = r.Status }; await repo.AddAsync(x); await repo.SaveChangesAsync(); return (new(x.EnrollmentId, x.StudentId, x.CourseId, x.EnrollDate, x.Status), null); }
    public async Task<(bool, string?)> UpdateEnrollmentAsync(int id, EnrollmentRequest r) { var x = await repo.FindAsync<Enrollment>(id); if (x is null) return (false, null); if (await repo.Students.SingleOrDefaultAsync(s => s.StudentId == r.StudentId) is null || await repo.Courses.SingleOrDefaultAsync(c => c.CourseId == r.CourseId) is null) return (true, "StudentId or CourseId does not exist."); if (await repo.Enrollments.AnyAsync(e => e.StudentId == r.StudentId && e.CourseId == r.CourseId && e.EnrollmentId != id)) return (true, "Student is already enrolled in this course."); x.StudentId = r.StudentId; x.CourseId = r.CourseId; x.EnrollDate = r.EnrollDate; x.Status = r.Status; await repo.SaveChangesAsync(); return (true, null); }
    public async Task<bool> DeleteEnrollmentAsync(int id) { var x = await repo.FindAsync<Enrollment>(id); if (x is null) return false; repo.Remove(x); await repo.SaveChangesAsync(); return true; }
}
