@host = http://localhost:5075

GET {{host}}/api/students?search=student&sort=fullName,-dateOfBirth&page=1&size=5&fields=studentId,fullName,email
Accept: application/json

###
GET {{host}}/api/enrollments?search=active&sort=-enrollDate&page=1&size=20&expand=student,course
Accept: application/json

###
GET {{host}}/api/students/1
Accept: application/json

### Content negotiation: XML
GET {{host}}/api/students?size=2&fields=studentId,fullName
Accept: application/xml

### Content negotiation: unsupported format -> 406
GET {{host}}/api/students
Accept: text/csv

### Request id is echoed in the X-Request-Id response header and in the request log
GET {{host}}/api/students/99999
Accept: application/json
X-Request-Id: demo-123
